export const COMPUTATION_STAGE_IDLE                         = 'COMPUTATION_STAGE_IDLE';
export const COMPUTATION_STAGE_START                        = 'COMPUTATION_STAGE_START';
export const COMPUTATION_STAGE_VALIDATION_REQUEST           = 'COMPUTATION_STAGE_VALIDATION_REQUEST';
export const COMPUTATION_STAGE_ANALYSIS_REQUEST             = 'COMPUTATION_STAGE_DATASET_ANALYSIS_REQUEST';
export const COMPUTATION_STAGE_HEATMAP_REQUEST              = 'COMPUTATION_STAGE_HEATMAP_REQUEST';