export const COMPUTATION_STAGE_INIT             = 'COMPUTATION_STAGE_INIT';
export const COMPUTATION_STAGE_ACCEPTED         = 'COMPUTATION_STAGE_ACCEPTED';
export const COMPUTATION_STAGE_REJECTED         = 'COMPUTATION_STAGE_REJECTED';
export const COMPUTATION_STAGE_ANALYZED         = 'COMPUTATION_STAGE_ANALYZED';
export const COMPUTATION_STAGE_IN_PROGRESS      = 'COMPUTATION_STAGE_IN_PROGRESS';
export const COMPUTATION_STAGE_COMPLETED        = 'COMPUTATION_STAGE_COMPLETED';
export const COMPUTATION_STAGE_ERRORED          = 'COMPUTATION_STAGE_ERRORED';