const wsEvents = {

    COMPUTATION_VALIDATION_START:           'COMPUTATION_VALIDATION_START',
    COMPUTATION_VALIDATION_SUCCESS:         'COMPUTATION_VALIDATION_SUCCESS',
    COMPUTATION_VALIDATION_FAIL:            'COMPUTATION_VALIDATION_FAIL',

    COMPUTATION_ANALYSIS_START:             'COMPUTATION_ANALYSIS_START',
    COMPUTATION_ANALYSIS_SUCCESS:           'COMPUTATION_ANALYSIS_SUCCESS',
    COMPUTATION_ANALYSIS_FAILED:            'COMPUTATION_ANALYSIS_FAILED',

    COMPUTATION_HEATMAP_START:              'COMPUTATION_HEATMAP_START',
    COMPUTATION_HEATMAP_SUCCESS:            'COMPUTATION_HEATMAP_SUCCESS',
    COMPUTATION_HEATMAP_FAIL:               'COMPUTATION_HEATMAP_FAIL',

    COMPUTATION_ERROR: 'COMPUTATION_ERROR',
};

module.exports = wsEvents;