const wsEvents = {

    HEATMAP_VALIDATION_START: 'HEATMAP_VALIDATION_START',
    HEATMAP_VALIDATION_SUCCESS: 'HEATMAP_VALIDATION_SUCCESS',
    HEATMAP_VALIDATION_FAIL: 'HEATMAP_VALIDATION_FAIL',
    HEATMAP_ANALYSIS_START: 'HEATMAP_ANALYSIS_START',
    HEATMAP_ANALYSIS_SUCCESS: 'HEATMAP_ANALYSIS_SUCCESS',
    HEATMAP_ANALYSIS_FAIL: 'HEATMAP_ANALYSIS_FAIL',
    HEATMAP_CONSTRUCTION_START: 'HEATMAP_CONSTRUCTION_START',
    HEATMAP_CONSTRUCTION_SUCCESS: 'HEATMAP_CONSTRUCTION_SUCCESS',
    HEATMAP_CONSTRUCTION_FAIL: 'HEATMAP_CONSTRUCTION_FAIL',

    HEATMAP_PROCESS_ERROR: 'HEATMAP_PROCESS_ERROR',
};

module.exports = wsEvents;