const wsEvents = {

    HEATMAP_VALIDATION_START: 'HEATMAP_VALIDATION_START',
    HEATMAP_VALIDATION_SUCCESS: 'HEATMAP_VALIDATION_SUCCESS',
    HEATMAP_VALIDATION_FAIL: 'HEATMAP_VALIDATION_FAIL',
    HEATMAP_ANALYSIS_START: 'HEATMAP_ANALYSIS_START',
    HEATMAP_ANALYSIS_SUCCESS: 'HEATMAP_ANALYSIS_SUCCESS',
    HEATMAP_ANALYSIS_FAIL: 'HEATMAP_ANALYSIS_FAIL',
    HEATMAP_COMPUTATION_UPDATE: 'HEATMAP_COMPUTATION_UPDATE',
};

module.exports = wsEvents;