const sharedConstants = {

    ANALYSIS_DATASET: 'ANALYSIS_DATASET',
    ANALYSIS_MEASUREMENTS: 'ANALYSIS_MEASUREMENTS',
    ANALYSIS_PSPT: 'ANALYSIS_PSPT',

    FETCH_TIMESERIES_DATA: 'FETCH_TIMESERIES_DATA',
};

module.exports = sharedConstants;